version: '3.8'

services:
  db:
    image: postgres:12.13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5430:5432
    healthcheck:
      test: pg_isready -U user -d postgres
      interval: 5s
      timeout: 2s
      retries: 5
  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database",  "postgresql://user:password@db:5432/postgres?sslmode=disable", "up" ]
    volumes:
      - ./migrations:/migrations
    restart: on-failure
    depends_on:
      - db
  node_app:
    build: .
    ports:
      - 3000:3000
    restart: on-failure:10
    environment:
      - PORT=3000
      - DATABASE_URL=db
    depends_on:
      - db